# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(969, 710)
        MainWindow.setStyleSheet("QWidget {\n"
"  background-color: #19232D;\n"
"  border: 0px solid #455364;\n"
"  padding: 0px;\n"
"  color: #E0E1E3;\n"
"  selection-background-color: #346792;\n"
"  selection-color: #E0E1E3;\n"
"    font-family : Ubuntu;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QWidget:disabled {\n"
"  background-color: #19232D;\n"
"  color: #9DA9B5;\n"
"  selection-background-color: #26486B;\n"
"  selection-color: #9DA9B5;\n"
"}\n"
"\n"
"QWidget::item:selected {\n"
"  background-color: #176B87;\n"
"}\n"
"\n"
"QWidget::item:hover:!selected {\n"
"  background-color: rgba(23, 107, 135,50%);\n"
"}\n"
"\n"
"QMainWindow::separator {\n"
"  background-color: #455364;\n"
"  border: 0px solid #19232D;\n"
"  spacing: 0px;\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QMainWindow::separator:hover {\n"
"  background-color: #60798B;\n"
"  border: 0px solid #1A72BB;\n"
"}\n"
"\n"
"/*-------------------------------------------------------------------------------------------*/\n"
"\n"
"QCheckBox {\n"
"  background-color: #19232D;\n"
"  color: #E0E1E3;\n"
"  spacing: 4px;\n"
"  outline: none;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"}\n"
"\n"
"\n"
"\n"
"QCheckBox QWidget:disabled {\n"
"  background-color: #19232D;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"  margin-left: 2px;\n"
"  height: 14px;\n"
"  width: 14px;\n"
"}\n"
"\n"
"/*-------------------------------------------------------------------------------------------*/\n"
"QScrollBar:horizontal {\n"
"  height: 16px;\n"
"  margin: 2px 16px 2px 16px;\n"
"  border: 1px solid white;\n"
"  border-radius: 4px;\n"
"  background-color: rgb(25, 35, 45);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"  background-color: #176B87;\n"
"  border: 1px solid #C9CDD0;\n"
"  border-radius: 4px;\n"
"  min-width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"  background-color: rgba(23, 107, 135,80%);\n"
"  border:#4169E1;\n"
"  border-radius: 4px;\n"
"  min-width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:focus {\n"
"  border: 1px solid red;\n"
"}\n"
"QScrollBar:vertical {\n"
"  background-color: rgb(25, 35, 45);\n"
"  width: 16px;\n"
"  margin: 16px 2px 16px 2px;\n"
"  border: 1px solid white;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical {\n"
"  background-color: #176B87;\n"
"  border: 1px solid #C9CDD0;\n"
"  min-height: 8px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"  background-color: rgba(23, 107, 135,80%);\n"
"  border: #9FCBFF;\n"
"  border-radius: 4px;\n"
"  min-height: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:focus {\n"
"  border: 1px solid #73C7FF;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"  margin: 0px 0px 0px 0px;\n"
"  border-image: url(\"qss_icons/light/rc/arrow_right_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: right;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover, QScrollBar::add-line:horizontal:on {\n"
"  border-image: url(\"qss_icons/light/rc/arrow_right.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: right;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"  margin: 3px 0px 3px 0px;\n"
"  border-image: url(\"qss_icons/light/rc/arrow_down_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: bottom;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on {\n"
"  border-image: url(\"qss_icons/light/rc/arrow_down.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: bottom;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"  margin: 0px 3px 0px 3px;\n"
"  border-image: url(\"qss_icons/light/rc/arrow_left_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: left;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on {\n"
"  border-image: url(\"qss_icons/light/rc/arrow_left.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: left;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"  margin: 3px 0px 3px 0px;\n"
"  border-image: url(\"qss_icons/light/rc/arrow_up_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover, QScrollBar::sub-line:vertical:on {\n"
"  border-image: url(\"qss_icons/light/rc/arrow_up.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"  background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"  background: none;\n"
"}\n"
"\n"
"/*----------------------------------------------------------------------------------------*/\n"
"QPushButton{\n"
" /*border:2px solid #05B8CC;*/\n"
" background-color: #176B87;\n"
" color:rgb(255, 255, 255);\n"
" border-radius: 10px;\n"
" font-weight:bold;\n"
" font-size:16px;\n"
"  transition: 500ms;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
" border: 1px solid #176B87;\n"
" background-color: rgba(23, 107, 135,80%)\n"
"}\n"
"QPushButton:pressed {\n"
" margin:1px 2px;\n"
" font-size: 15px;\n"
"}\n"
"/*----------------------------------------------------------------------------------------*/\n"
"QTabBar::tab {\n"
"    background-color: #455364;\n"
"    border: 3px solid #19232D;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    color: #E0E1E3;\n"
"    font-family: Ubuntu;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: #455364;\n"
"    border: 3px solid #19232D;\n"
"    border-radius: 10px;\n"
"    padding: 4px 8px;\n"
"    color: #E0E1E3;\n"
"    font-family: Ubuntu;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color:rgba(69,83,100,60%);\n"
"    color: white;\n"
"    margin-top: 3px;\n"
"    border-bottom: 3px solid white;\n"
"}\n"
"QPlotWidget{\n"
" background-color:(25, 35, 45, 0.8)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_start_contour = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_contour.setObjectName("btn_start_contour")
        self.gridLayout.addWidget(self.btn_start_contour, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_ht = QtWidgets.QWidget()
        self.tab_ht.setObjectName("tab_ht")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_ht)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.chk_lines = QtWidgets.QCheckBox(self.tab_ht)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chk_lines.sizePolicy().hasHeightForWidth())
        self.chk_lines.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.chk_lines.setFont(font)
        self.chk_lines.setChecked(True)
        self.chk_lines.setObjectName("chk_lines")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.chk_lines)
        self.verticalLayout_7.addWidget(self.chk_lines)
        self.chk_circles = QtWidgets.QCheckBox(self.tab_ht)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chk_circles.sizePolicy().hasHeightForWidth())
        self.chk_circles.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.chk_circles.setFont(font)
        self.chk_circles.setObjectName("chk_circles")
        self.buttonGroup.addButton(self.chk_circles)
        self.verticalLayout_7.addWidget(self.chk_circles)
        self.chk_ellipses = QtWidgets.QCheckBox(self.tab_ht)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chk_ellipses.sizePolicy().hasHeightForWidth())
        self.chk_ellipses.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.chk_ellipses.setFont(font)
        self.chk_ellipses.setObjectName("chk_ellipses")
        self.buttonGroup.addButton(self.chk_ellipses)
        self.verticalLayout_7.addWidget(self.chk_ellipses)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_ht)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("\n"
"font-size:15px;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.lines = QtWidgets.QWidget()
        self.lines.setObjectName("lines")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.lines)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.lines)
        self.widget.setObjectName("widget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_theta = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_theta.sizePolicy().hasHeightForWidth())
        self.label_theta.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_theta.setFont(font)
        self.label_theta.setObjectName("label_theta")
        self.horizontalLayout_8.addWidget(self.label_theta)
        self.label_theta_value = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_theta_value.sizePolicy().hasHeightForWidth())
        self.label_theta_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_theta_value.setFont(font)
        self.label_theta_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_theta_value.setObjectName("label_theta_value")
        self.horizontalLayout_8.addWidget(self.label_theta_value)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.slider_theta = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_theta.sizePolicy().hasHeightForWidth())
        self.slider_theta.setSizePolicy(sizePolicy)
        self.slider_theta.setOrientation(QtCore.Qt.Horizontal)
        self.slider_theta.setObjectName("slider_theta")
        self.verticalLayout_9.addWidget(self.slider_theta)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_thresh = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_thresh.sizePolicy().hasHeightForWidth())
        self.label_thresh.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_thresh.setFont(font)
        self.label_thresh.setObjectName("label_thresh")
        self.horizontalLayout_2.addWidget(self.label_thresh)
        self.label_thresh_value = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_thresh_value.sizePolicy().hasHeightForWidth())
        self.label_thresh_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_thresh_value.setFont(font)
        self.label_thresh_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_thresh_value.setObjectName("label_thresh_value")
        self.horizontalLayout_2.addWidget(self.label_thresh_value)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.slider_thresh = QtWidgets.QSlider(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_thresh.sizePolicy().hasHeightForWidth())
        self.slider_thresh.setSizePolicy(sizePolicy)
        self.slider_thresh.setOrientation(QtCore.Qt.Horizontal)
        self.slider_thresh.setObjectName("slider_thresh")
        self.verticalLayout_10.addWidget(self.slider_thresh)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.gridLayout_3.addWidget(self.widget, 1, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_rho = QtWidgets.QLabel(self.lines)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rho.sizePolicy().hasHeightForWidth())
        self.label_rho.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_rho.setFont(font)
        self.label_rho.setObjectName("label_rho")
        self.horizontalLayout_10.addWidget(self.label_rho)
        self.label_rho_value = QtWidgets.QLabel(self.lines)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_rho_value.sizePolicy().hasHeightForWidth())
        self.label_rho_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_rho_value.setFont(font)
        self.label_rho_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rho_value.setObjectName("label_rho_value")
        self.horizontalLayout_10.addWidget(self.label_rho_value)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.slider_rho = QtWidgets.QSlider(self.lines)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_rho.sizePolicy().hasHeightForWidth())
        self.slider_rho.setSizePolicy(sizePolicy)
        self.slider_rho.setOrientation(QtCore.Qt.Horizontal)
        self.slider_rho.setObjectName("slider_rho")
        self.verticalLayout_8.addWidget(self.slider_rho)
        self.gridLayout_3.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.lines)
        self.circles = QtWidgets.QWidget()
        self.circles.setObjectName("circles")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.circles)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.widget_2 = QtWidgets.QWidget(self.circles)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_min_radius = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min_radius.sizePolicy().hasHeightForWidth())
        self.label_min_radius.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_min_radius.setFont(font)
        self.label_min_radius.setObjectName("label_min_radius")
        self.horizontalLayout_11.addWidget(self.label_min_radius)
        self.label_min_radius_value = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min_radius_value.sizePolicy().hasHeightForWidth())
        self.label_min_radius_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_min_radius_value.setFont(font)
        self.label_min_radius_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_min_radius_value.setObjectName("label_min_radius_value")
        self.horizontalLayout_11.addWidget(self.label_min_radius_value)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.slider_circle_min_radius = QtWidgets.QSlider(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_circle_min_radius.sizePolicy().hasHeightForWidth())
        self.slider_circle_min_radius.setSizePolicy(sizePolicy)
        self.slider_circle_min_radius.setOrientation(QtCore.Qt.Horizontal)
        self.slider_circle_min_radius.setObjectName("slider_circle_min_radius")
        self.verticalLayout_13.addWidget(self.slider_circle_min_radius)
        self.verticalLayout_12.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_max_radius = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_max_radius.sizePolicy().hasHeightForWidth())
        self.label_max_radius.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_max_radius.setFont(font)
        self.label_max_radius.setObjectName("label_max_radius")
        self.horizontalLayout_12.addWidget(self.label_max_radius)
        self.label_max_radius_value = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_max_radius_value.sizePolicy().hasHeightForWidth())
        self.label_max_radius_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_max_radius_value.setFont(font)
        self.label_max_radius_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_max_radius_value.setObjectName("label_max_radius_value")
        self.horizontalLayout_12.addWidget(self.label_max_radius_value)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.slider_circle_max_radius = QtWidgets.QSlider(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_circle_max_radius.sizePolicy().hasHeightForWidth())
        self.slider_circle_max_radius.setSizePolicy(sizePolicy)
        self.slider_circle_max_radius.setOrientation(QtCore.Qt.Horizontal)
        self.slider_circle_max_radius.setObjectName("slider_circle_max_radius")
        self.verticalLayout_14.addWidget(self.slider_circle_max_radius)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_circles_threshold = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_circles_threshold.sizePolicy().hasHeightForWidth())
        self.label_circles_threshold.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_circles_threshold.setFont(font)
        self.label_circles_threshold.setObjectName("label_circles_threshold")
        self.horizontalLayout_13.addWidget(self.label_circles_threshold)
        self.label_circles_threshold_value = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_circles_threshold_value.sizePolicy().hasHeightForWidth())
        self.label_circles_threshold_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_circles_threshold_value.setFont(font)
        self.label_circles_threshold_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_circles_threshold_value.setObjectName("label_circles_threshold_value")
        self.horizontalLayout_13.addWidget(self.label_circles_threshold_value)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.slider_circle_threshold = QtWidgets.QSlider(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_circle_threshold.sizePolicy().hasHeightForWidth())
        self.slider_circle_threshold.setSizePolicy(sizePolicy)
        self.slider_circle_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.slider_circle_threshold.setObjectName("slider_circle_threshold")
        self.verticalLayout_15.addWidget(self.slider_circle_threshold)
        self.verticalLayout_14.addLayout(self.verticalLayout_15)
        self.verticalLayout_12.addLayout(self.verticalLayout_14)
        self.verticalLayout_33.addWidget(self.widget_2)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_min_dist = QtWidgets.QLabel(self.circles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min_dist.sizePolicy().hasHeightForWidth())
        self.label_min_dist.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_min_dist.setFont(font)
        self.label_min_dist.setObjectName("label_min_dist")
        self.horizontalLayout_26.addWidget(self.label_min_dist)
        self.label_min_dist_value = QtWidgets.QLabel(self.circles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min_dist_value.sizePolicy().hasHeightForWidth())
        self.label_min_dist_value.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_min_dist_value.setFont(font)
        self.label_min_dist_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_min_dist_value.setObjectName("label_min_dist_value")
        self.horizontalLayout_26.addWidget(self.label_min_dist_value)
        self.verticalLayout_32.addLayout(self.horizontalLayout_26)
        self.slider_circle_min_dist = QtWidgets.QSlider(self.circles)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_circle_min_dist.sizePolicy().hasHeightForWidth())
        self.slider_circle_min_dist.setSizePolicy(sizePolicy)
        self.slider_circle_min_dist.setOrientation(QtCore.Qt.Horizontal)
        self.slider_circle_min_dist.setObjectName("slider_circle_min_dist")
        self.verticalLayout_32.addWidget(self.slider_circle_min_dist)
        self.verticalLayout_33.addLayout(self.verticalLayout_32)
        self.stackedWidget.addWidget(self.circles)
        self.ellipses = QtWidgets.QWidget()
        self.ellipses.setObjectName("ellipses")
        self.stackedWidget.addWidget(self.ellipses)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.gridLayout_5.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.wgt_hough_input = PlotWidget(self.tab_ht)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_hough_input.sizePolicy().hasHeightForWidth())
        self.wgt_hough_input.setSizePolicy(sizePolicy)
        self.wgt_hough_input.setStyleSheet("background: crimson;")
        self.wgt_hough_input.setObjectName("wgt_hough_input")
        self.gridLayout_5.addWidget(self.wgt_hough_input, 0, 0, 1, 1)
        self.wgt_hough_edges = PlotWidget(self.tab_ht)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_hough_edges.sizePolicy().hasHeightForWidth())
        self.wgt_hough_edges.setSizePolicy(sizePolicy)
        self.wgt_hough_edges.setStyleSheet("background: #8B0000;")
        self.wgt_hough_edges.setObjectName("wgt_hough_edges")
        self.gridLayout_5.addWidget(self.wgt_hough_edges, 1, 0, 1, 1)
        self.btn_hough_apply = QtWidgets.QPushButton(self.tab_ht)
        self.btn_hough_apply.setObjectName("btn_hough_apply")
        self.gridLayout_5.addWidget(self.btn_hough_apply, 3, 0, 1, 1)
        self.wgt_hough_output = PlotWidget(self.tab_ht)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_hough_output.sizePolicy().hasHeightForWidth())
        self.wgt_hough_output.setSizePolicy(sizePolicy)
        self.wgt_hough_output.setStyleSheet("background: deep blue;")
        self.wgt_hough_output.setObjectName("wgt_hough_output")
        self.gridLayout_5.addWidget(self.wgt_hough_output, 0, 1, 4, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.tabWidget.addTab(self.tab_ht, "")
        self.tab_canny = QtWidgets.QWidget()
        self.tab_canny.setObjectName("tab_canny")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_canny)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.wgt_canny_input = PlotWidget(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_canny_input.sizePolicy().hasHeightForWidth())
        self.wgt_canny_input.setSizePolicy(sizePolicy)
        self.wgt_canny_input.setMinimumSize(QtCore.QSize(300, 0))
        self.wgt_canny_input.setStyleSheet("background: crimson;")
        self.wgt_canny_input.setObjectName("wgt_canny_input")
        self.verticalLayout_6.addWidget(self.wgt_canny_input)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_sigma = QtWidgets.QLabel(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sigma.sizePolicy().hasHeightForWidth())
        self.label_sigma.setSizePolicy(sizePolicy)
        self.label_sigma.setObjectName("label_sigma")
        self.horizontalLayout_3.addWidget(self.label_sigma)
        self.label_sigma_value = QtWidgets.QLabel(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sigma_value.sizePolicy().hasHeightForWidth())
        self.label_sigma_value.setSizePolicy(sizePolicy)
        self.label_sigma_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sigma_value.setObjectName("label_sigma_value")
        self.horizontalLayout_3.addWidget(self.label_sigma_value)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.slider_canny_sigma = QtWidgets.QSlider(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_canny_sigma.sizePolicy().hasHeightForWidth())
        self.slider_canny_sigma.setSizePolicy(sizePolicy)
        self.slider_canny_sigma.setOrientation(QtCore.Qt.Horizontal)
        self.slider_canny_sigma.setObjectName("slider_canny_sigma")
        self.verticalLayout_4.addWidget(self.slider_canny_sigma)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_Lthresh = QtWidgets.QLabel(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Lthresh.sizePolicy().hasHeightForWidth())
        self.label_Lthresh.setSizePolicy(sizePolicy)
        self.label_Lthresh.setObjectName("label_Lthresh")
        self.horizontalLayout_4.addWidget(self.label_Lthresh)
        self.label_Lthresh_value = QtWidgets.QLabel(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Lthresh_value.sizePolicy().hasHeightForWidth())
        self.label_Lthresh_value.setSizePolicy(sizePolicy)
        self.label_Lthresh_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Lthresh_value.setObjectName("label_Lthresh_value")
        self.horizontalLayout_4.addWidget(self.label_Lthresh_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.slider_canny_low = QtWidgets.QSlider(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_canny_low.sizePolicy().hasHeightForWidth())
        self.slider_canny_low.setSizePolicy(sizePolicy)
        self.slider_canny_low.setOrientation(QtCore.Qt.Horizontal)
        self.slider_canny_low.setObjectName("slider_canny_low")
        self.verticalLayout_3.addWidget(self.slider_canny_low)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_Hthresh = QtWidgets.QLabel(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Hthresh.sizePolicy().hasHeightForWidth())
        self.label_Hthresh.setSizePolicy(sizePolicy)
        self.label_Hthresh.setObjectName("label_Hthresh")
        self.horizontalLayout_5.addWidget(self.label_Hthresh)
        self.label_Hthresh_value = QtWidgets.QLabel(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Hthresh_value.sizePolicy().hasHeightForWidth())
        self.label_Hthresh_value.setSizePolicy(sizePolicy)
        self.label_Hthresh_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Hthresh_value.setObjectName("label_Hthresh_value")
        self.horizontalLayout_5.addWidget(self.label_Hthresh_value)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.slider_canny_high = QtWidgets.QSlider(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_canny_high.sizePolicy().hasHeightForWidth())
        self.slider_canny_high.setSizePolicy(sizePolicy)
        self.slider_canny_high.setOrientation(QtCore.Qt.Horizontal)
        self.slider_canny_high.setObjectName("slider_canny_high")
        self.verticalLayout_2.addWidget(self.slider_canny_high)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_k_size = QtWidgets.QLabel(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_k_size.sizePolicy().hasHeightForWidth())
        self.label_k_size.setSizePolicy(sizePolicy)
        self.label_k_size.setObjectName("label_k_size")
        self.horizontalLayout_6.addWidget(self.label_k_size)
        self.label_k_size_value = QtWidgets.QLabel(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_k_size_value.sizePolicy().hasHeightForWidth())
        self.label_k_size_value.setSizePolicy(sizePolicy)
        self.label_k_size_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_size_value.setObjectName("label_k_size_value")
        self.horizontalLayout_6.addWidget(self.label_k_size_value)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.slider_canny_k_size = QtWidgets.QSlider(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_canny_k_size.sizePolicy().hasHeightForWidth())
        self.slider_canny_k_size.setSizePolicy(sizePolicy)
        self.slider_canny_k_size.setOrientation(QtCore.Qt.Horizontal)
        self.slider_canny_k_size.setObjectName("slider_canny_k_size")
        self.verticalLayout.addWidget(self.slider_canny_k_size)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.wgt_canny_output = PlotWidget(self.tab_canny)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_canny_output.sizePolicy().hasHeightForWidth())
        self.wgt_canny_output.setSizePolicy(sizePolicy)
        self.wgt_canny_output.setStyleSheet("background: deep blue;")
        self.wgt_canny_output.setObjectName("wgt_canny_output")
        self.horizontalLayout_7.addWidget(self.wgt_canny_output)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_canny, "")
        self.tab_active_contour = QtWidgets.QWidget()
        self.tab_active_contour.setObjectName("tab_active_contour")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_active_contour)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.wgt_contour_input = PlotWidget(self.tab_active_contour)
        self.wgt_contour_input.setSizeIncrement(QtCore.QSize(1, 1))
        self.wgt_contour_input.setBaseSize(QtCore.QSize(200, 200))
        self.wgt_contour_input.setStyleSheet("background: crimson;")
        self.wgt_contour_input.setObjectName("wgt_contour_input")
        self.horizontalLayout_9.addWidget(self.wgt_contour_input)
        self.wgt_contour_output = PlotWidget(self.tab_active_contour)
        self.wgt_contour_output.setSizeIncrement(QtCore.QSize(1, 1))
        self.wgt_contour_output.setBaseSize(QtCore.QSize(200, 200))
        self.wgt_contour_output.setStyleSheet("background: deep blue;")
        self.wgt_contour_output.setObjectName("wgt_contour_output")
        self.horizontalLayout_9.addWidget(self.wgt_contour_output)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_active_contour, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 969, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Image = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.menuFile.addAction(self.actionOpen_Image)
        self.menubar.addAction(self.menuFile.menuAction())
        self.label_theta.setBuddy(self.slider_theta)
        self.label_theta_value.setBuddy(self.slider_theta)
        self.label_thresh.setBuddy(self.slider_thresh)
        self.label_thresh_value.setBuddy(self.slider_theta)
        self.label_rho.setBuddy(self.slider_rho)
        self.label_rho_value.setBuddy(self.slider_theta)
        self.label_min_radius.setBuddy(self.slider_rho)
        self.label_min_radius_value.setBuddy(self.slider_theta)
        self.label_max_radius.setBuddy(self.slider_theta)
        self.label_max_radius_value.setBuddy(self.slider_theta)
        self.label_circles_threshold.setBuddy(self.slider_thresh)
        self.label_circles_threshold_value.setBuddy(self.slider_theta)
        self.label_min_dist.setBuddy(self.slider_rho)
        self.label_min_dist_value.setBuddy(self.slider_theta)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.slider_rho.valueChanged['int'].connect(self.label_rho_value.setNum) # type: ignore
        self.slider_theta.valueChanged['int'].connect(self.label_theta_value.setNum) # type: ignore
        self.slider_thresh.valueChanged['int'].connect(self.label_thresh_value.setNum) # type: ignore
        self.slider_circle_min_dist.valueChanged['int'].connect(self.label_min_dist_value.setNum) # type: ignore
        self.slider_circle_threshold.valueChanged['int'].connect(self.label_circles_threshold_value.setNum) # type: ignore
        self.slider_circle_max_radius.valueChanged['int'].connect(self.label_max_radius_value.setNum) # type: ignore
        self.slider_circle_min_radius.valueChanged['int'].connect(self.label_min_radius_value.setNum) # type: ignore
        self.slider_canny_sigma.valueChanged['int'].connect(self.label_sigma_value.setNum) # type: ignore
        self.slider_canny_low.valueChanged['int'].connect(self.label_Lthresh_value.setNum) # type: ignore
        self.slider_canny_high.valueChanged['int'].connect(self.label_Hthresh_value.setNum) # type: ignore
        self.slider_canny_k_size.valueChanged['int'].connect(self.label_k_size_value.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_start_contour.setText(_translate("MainWindow", "Start Contour"))
        self.chk_lines.setText(_translate("MainWindow", "Lines"))
        self.chk_circles.setText(_translate("MainWindow", "Circles"))
        self.chk_ellipses.setText(_translate("MainWindow", "Ellipses"))
        self.label_theta.setText(_translate("MainWindow", "Theta:"))
        self.label_theta_value.setText(_translate("MainWindow", "0"))
        self.label_thresh.setText(_translate("MainWindow", "Threshold"))
        self.label_thresh_value.setText(_translate("MainWindow", "0"))
        self.label_rho.setText(_translate("MainWindow", "Rho"))
        self.label_rho_value.setText(_translate("MainWindow", "0"))
        self.label_min_radius.setText(_translate("MainWindow", "Min Radius:"))
        self.label_min_radius_value.setText(_translate("MainWindow", "0"))
        self.label_max_radius.setText(_translate("MainWindow", "Max Radius:"))
        self.label_max_radius_value.setText(_translate("MainWindow", "0"))
        self.label_circles_threshold.setText(_translate("MainWindow", "Threshold:"))
        self.label_circles_threshold_value.setText(_translate("MainWindow", "0"))
        self.label_min_dist.setText(_translate("MainWindow", "Min Dist:"))
        self.label_min_dist_value.setText(_translate("MainWindow", "0"))
        self.btn_hough_apply.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ht), _translate("MainWindow", "Hough Transform"))
        self.label_sigma.setText(_translate("MainWindow", "Sigma:"))
        self.label_sigma_value.setText(_translate("MainWindow", "1"))
        self.label_Lthresh.setText(_translate("MainWindow", "Low Threshold:"))
        self.label_Lthresh_value.setText(_translate("MainWindow", "0"))
        self.label_Hthresh.setText(_translate("MainWindow", "High Threshold:"))
        self.label_Hthresh_value.setText(_translate("MainWindow", "1"))
        self.label_k_size.setText(_translate("MainWindow", "Kernel Size:"))
        self.label_k_size_value.setText(_translate("MainWindow", "3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_canny), _translate("MainWindow", "Canny"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_active_contour), _translate("MainWindow", "Active Contour"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_Image.setText(_translate("MainWindow", "Open Image"))
        self.actionOpen_Image.setShortcut(_translate("MainWindow", "Ctrl+O"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
